language: cpp
dist: trusty
sudo: required
compiler:
  - gcc
  - clang
os:
  - linux
before_install:
  - pushd ..
  - wget http://downloads.arduino.cc/arduino-1.6.11-linux64.tar.xz
  - tar xf arduino-1.6.11-linux64.tar.xz
  - popd
install:
  - git submodule sync --recursive
  - git submodule update --init --recursive
script:
  - make all ARDUINO_PATH=$HOME/arduino-1.6.11
  - make check
