#! /bin/sh
## This is a terrible hack, please don't hurt me.

set -e

MAX_PROG_SIZE=28672

output="$($@ | grep "\\(Program\\|Data\\):" | sed -e 's,^,  - ,' && echo)"

PROGSIZE="$(echo "${output}" | grep Program: | cut -d: -f2 | awk '{print $1}')"

PERCENT=$(cat <<EOF
scale=2
${PROGSIZE} / ${MAX_PROG_SIZE} * 100
EOF
       )

PERCENT=$(printf %02.01f $(echo "${PERCENT}" | bc -q))

echo "${output}" | sed -e "s,\(Program:.*\)(\([0-9\.]*%\) Full),\1(${PERCENT}% Full),"
