# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "A.K.E.L.A."
title_separator          : "-"
name                     : &name "Gergely Nagy"
description              : &description "Animated Keyboard Extension Library for Arduino"
url                      : https://algernon.github.io
baseurl                  : "/Akela"
repository               : "algernon/Akela"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
words_per_minute         : 200

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "algernoone"
#og_image                 : "/assets/images/site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/algernoone"

# Analytics
analytics:
  provider               : "custom"

# Site Author
author:
  name             : *name
  bio              : "A tiny mouse, a hacker."
  location         :
  email            :
  uri              : "https://asylum.madhouse-project.org/"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "algernon"
  google_plus      :
  keybase          : "algernon"
  instagram        :
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : *twitter
  vine             :
  weibo            :
  xing             :
  youtube          :


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      comments: false
  # _guides
  - scope:
      path: ""
      type: guides
    values:
      layout: single
      read_time: true
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "guides"

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Europe/Budapest

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-gist

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-gist

compress_html:
  clippings: all
